## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [31]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()

City_ID                       City Country  Max Temp Current Description  \
0        0  Santa Isabel Do Rio Negro      BR     80.89     overcast clouds   
1        1                   Acapulco      MX     85.82           clear sky   
2        5                    Rikitea      PF     76.93          light rain   
3        6                   Celestun      MX     76.91     overcast clouds   
4        7                  Esperance      AU     62.44           clear sky   

       Lat       Lng                 Hotel Name  
0  -0.4139  -65.0192                  Hotel GSA  
1  16.8634  -99.8901  HS Hotsson Smart Acapulco  
2 -23.1203 -134.9692            People ThankYou  
3  20.8667  -90.4000               Posada Lilia  
4 -33.8667  121.9000      Hospitality Esperance

In [32]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [61]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig



Figure(layout=FigureLayout(height='420px'))

In [48]:
# From the map above pick 4 cities and create a vacation itinerary 
# route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' 
# using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == 'San Isidro'] 
vacation_start

City_ID        City Country  Max Temp Current Description      Lat    Lng  \
68      140  San Isidro      PE     76.59       broken clouds -12.1167 -77.05   

       Hotel Name  
68  Soul Mate-Inn

In [49]:
# 5. Create DataFrames for each city by filtering the 'vacation_df' 
# using the loc method. 
vacation_end = vacation_df.loc[vacation_df['City'] == 'San Isidro']
vacation_end

City_ID        City Country  Max Temp Current Description      Lat    Lng  \
68      140  San Isidro      PE     76.59       broken clouds -12.1167 -77.05   

       Hotel Name  
68  Soul Mate-Inn

In [46]:
# 5. Create DataFrames for each city by filtering the 'vacation_df' 
# using the loc method. 
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Huarmey']
vacation_stop1

City_ID     City Country  Max Temp Current Description      Lat      Lng  \
234      481  Huarmey      PE     75.22       broken clouds -10.0681 -78.1522   

        Hotel Name  
234  Hotel Miramar

In [47]:
# 5. Create DataFrames for each city by filtering the 'vacation_df' 
# using the loc method. 
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Paramonga'] 
vacation_stop2

City_ID       City Country  Max Temp Current Description      Lat  \
330      692  Paramonga      PE     75.11       broken clouds -10.6667   

         Lng                    Hotel Name  
330 -77.8333  HOSTAL MI CHALET - PARAMONGA

In [50]:
# 5. Create DataFrames for each city by filtering the 'vacation_df' 
# using the loc method.
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Hualmay']
vacation_stop3

City_ID     City Country  Max Temp Current Description      Lat      Lng  \
278      571  Hualmay      PE     75.51    scattered clouds -11.0964 -77.6139   

                    Hotel Name  
278  Hotel Villa Kitzia Huacho

In [56]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start.iloc[0,5:7].to_numpy()
# array([-12.1167, -77.05], dtype=object)
end = vacation_end.iloc[0,5:7].to_numpy()
# array([-12.1167, -77.05], dtype=object)
stop1 = vacation_stop1.iloc[0,5:7].to_numpy()
# array([-10.0681, -78.1522], dtype=object)
stop2 = vacation_stop2.iloc[0,5:7].to_numpy()
# array([-10.6667, -77.8333], dtype=object)
stop3 = vacation_stop3.iloc[0,5:7].to_numpy()
# array([-11.0964, -77.6139], dtype=object)
start


array([-12.1167, -77.05], dtype=object)

In [57]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
travel_route = gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode="DRIVING" or "BICYCLING" or "WALKING")
fig.add_layer(travel_route)
fig

Figure(layout=FigureLayout(height='420px'))

In [58]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, 
                          vacation_stop2, vacation_stop3]
                         ,ignore_index=True)
itinerary_df

City_ID        City Country  Max Temp Current Description      Lat  \
0      140  San Isidro      PE     76.59       broken clouds -12.1167   
1      481     Huarmey      PE     75.22       broken clouds -10.0681   
2      692   Paramonga      PE     75.11       broken clouds -10.6667   
3      571     Hualmay      PE     75.51    scattered clouds -11.0964   

       Lng                    Hotel Name  
0 -77.0500                 Soul Mate-Inn  
1 -78.1522                 Hotel Miramar  
2 -77.8333  HOSTAL MI CHALET - PARAMONGA  
3 -77.6139     Hotel Villa Kitzia Huacho

In [59]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [60]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))